#cloud-config

---
coreos:
  update:
    reboot-strategy: etcd-lock

  etcd2:
    discovery-srv: ${ internal-tld }
    peer-trusted-ca-file: ${ cert-path }/root.pem
    peer-client-cert-auth: true
    peer-cert-file: ${ cert-path }/etcd.pem
    peer-key-file: ${ cert-path }/etcd-key.pem
    proxy: on

  units:
    - name: etcd2.service
      command: start
      drop-ins:
        - name: 50-wait-on-cloud-config
          content: |
            [Unit]
            After=coreos-cloudinit.service
            Requires=coreos-cloudinit.service

write-files:
  - path: ${ cert-path }/root.pem
    permissions: "0644"
    owner: root
    content: ${ jsonencode(root-cert) }

  - path: ${ cert-path }/etcd.pem
    permissions: "0644"
    owner: root
    content: ${ jsonencode(etcd-cert) }

  - path: ${ cert-path }/etcd-key.pem
    permissions: "0644"
    owner: root
    content: ${ jsonencode(etcd-key) }
